export const CONSTANTS = {
  Email: "Email",
  Password: "Password",
  email: "email",
  password: "password",
  text: "text",
  user: "user",
  login: "login",
  Button: "Button",
  EmailPlaceholder: "Enter your email",
  PasswordPlaceholder: "Enter Password",
  confirmPassword: "confirmPassword",
  newPassword: "newPassword",
  otp: "otp",
  NewPasswordPlaceholder: "Enter password",
  ConfirmPasswordPlaceholder: "Confirm password",
  ConfirmPassword: "Confirm Password",
  NewPassword: "New Password",
  OTP: "OTP",
  OTPPlaceholder: "Enter OTP",
};
