export const CONSTANTS = {
  Email: "Email",
  Password: "Password",
  email: "email",
  password: "password",
  text: "text",
  user: "user",
  login: "login",
  Button: "Button",
  confirmPassword: "confirm Password",
  Confirmpassword: "Confirm password",
  newPassword: "new Password",
  otp: "otp",
  ConfirmPassword: "Confirm Password",
  NewPassword: "New Password",
  OTP: "OTP",
};
