export const CONSTANTS = {
    Email: "Email",
    Password: "Password",
    email: "email",
    text: "text",
    password: "password",
    user: "user",
    login: "login",
    Button: "Button",
    firstName: "firstName",
    first_name: "first_name",
    EmailPlaceholder: "Enter your email",
    PasswordPlaceholder: "Enter Password",
    confirmPassword: "confirmPassword",
    newPassword: "newPassword",
    otp: "otp",
    NewPasswordPlaceholder: "Enter new password",
    ConfirmPasswordPlaceholder: "Confirm new password",
    ConfirmPassword: "Confirm Password",
    NewPassword: "New Password",
    OTP: "OTP",
    OTPPlaceholder: "Enter OTP",
}